#!/bin/bash


branch=$(git rev-parse --symbolic --abbrev-ref HEAD)

if [[ "master" == "$branch" || "devel" == "$branch" ]]; then
	echo "On branch $branch. Add --no-verify argument to commit to this branch."
	exit 1
fi

exit 0
